add new event
xen0n/go-workwx pull request #106
Opened 2022-08-27 09:05 UTC by shuaiyy

新增事件消息类型：

- 企业微信App菜单事件
   -  点击菜单 `click`
   - 点击菜单链接 `view`
- 未知事件类型，用于debug

2022-08-27 09:28 UTC, xen0n requested changes
Thanks!

大体 okay，不过具体姿势有点问题，提交信息（commit message）也稍微认真按照规范写一下会比较好（有时候别人代码写得 OK 除了 commit message 没有按 conventional 格式来，为了优化新人体验，也就算了，这次你反正也得 squash 你的提交所以就一并要求了）

2022-08-27 09:28 UTC, xen0n commented on rx_msg.go
> +// EventAppMenuClick  点击菜单事件
请照着其他同类方法的注释写这些新方法的注释

2022-08-27 09:28 UTC, xen0n commented on rx_msg.go
> +	y, ok := m.extras.(*rxEventUnknow)
`rxEventUnknow` 拼错了

2022-08-27 09:28 UTC, xen0n commented on rx_msg.md.go
> +)
你得改相应的 md 文件然后 `go generate` 吧，否则下次这些更改就没了

你在写这个文件的时候，编辑器应该警告你不要动它了，文件头也告诉你这个文件怎么生成的了。。。

2022-08-27 09:29 UTC, xen0n commented
1. 你写在这个 PR 正文的那段话就是不错的 commit message
2. 如果这是你工作上要用的东西，尽量不要加班，周末对自己好一点 ;-)

2022-08-27 11:07 UTC, shuaiyy commented
> 1. 你写在这个 PR 正文的那段话就是不错的 commit message
> 2. 如果这是你工作上要用的东西，尽量不要加班，周末对自己好一点 ;-)

thx! 大佬看的好认真，我下周改一下；确实没怎么看代码规范，也没看项目的代码逻辑，只想着实现我需要的功能了T.T

2022-09-05 12:01 UTC, xen0n commented
Ping

2022-09-07 05:27 UTC, xen0n reviewed
Mostly LGTM except one nit, thanks!

2022-09-07 05:27 UTC, xen0n commented on docs/rx_msg.md
> +const EventTypeAppUnSubscribe = "unsubscribe"
Unsubscribe 是一个词，只需要大写一个首字母即可

2022-09-07 05:28 UTC, xen0n commented
改好之后，rebase（不允许有 merge 提交），改提交说明

或者我帮你搞？

2022-09-07 06:08 UTC, shuaiyy commented
> 改好之后，rebase（不允许有 merge 提交），squash 成单个提交，改提交说明
> 
> 或者我帮你搞？

我弄吧，

2022-09-07 08:43 UTC, xen0n commented on docs/rx_msg.md
> +const EventTypeUnknown = ".*"
这个没用到吧。。实际上他也不会被当作正则来用（未知消息类型，直接看取到的值类型就知道他“未知”了），去掉就好了

2022-09-07 11:06 UTC, shuaiyy commented on docs/rx_msg.md
> +const EventTypeUnknown = ".*"
好的

2022-09-08 07:11 UTC, xen0n commented
虽然你的 commit message 里“3. 未知事件类型: sdk中未定义的事件类型, 返回原始的body, 用于debug”这里序号 3 重复了，但无伤大雅，先给你合了

bors r+

十分感谢贡献！

2022-09-08 07:11 UTC, xen0n approved these changes

2022-09-08 07:12 UTC, merged